// sidebars.js
import apiSidebarItems from './docs/api/sidebar'; // generated by openapi plugin

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Advanced settings',
      items: [{ type: 'autogenerated', dirName: 'advance-settings' }],
    },
    {
      type: 'category',
      label: 'Notifications',
      items: [{ type: 'autogenerated', dirName: 'notifications' }],
    },

    // API: use the generated grouped items (tagGroups)
    {
      type: 'category',
      label: 'API',
      collapsible: true,
      collapsed: true,
      items: apiSidebarItems,
    },
  ],
};
